group:
  - id: default
    files:
      - source: workflows/base/basic-linters.yml
        dest: .github/workflows/basic-linters.yml
      - source: LICENSE
        dest: LICENSE
    repos: |-
      valitydev/damsel
      valitydev/newway
  - id: proto
    files:
      - source: workflows/proto/
        dest: .github/workflows/
        deleteOrphaned: true
        exclude: |
          basic-linters.yml
    repos: valitydev/damsel
  - id: java
    files:
      - source: codeowners/java
        dest: CODEOWNERS
        replace: false
    repos: |-
      valitydev/adapter-bank-payout-spring-boot-starter
      valitydev/adapter-bank-spring-boot-starter
      valitydev/adapter-bank-spring-boot-starter-test
      valitydev/adapter-client-lib
      valitydev/adapter-common-lib
      valitydev/adapter-flow-lib
      valitydev/adapter-thrift-lib
      valitydev/analytics
      valitydev/anapi-v2
      valitydev/claim-management
      valitydev/clickhouse-test
      valitydev/columbus
      valitydev/db-common-lib
      valitydev/deanonimus
      valitydev/error-mapping-java
      valitydev/fistful-magista
      valitydev/fistful-reporter
      valitydev/fraudbusters
      valitydev/fraudbusters-api
      valitydev/fraudbusters-examples
      valitydev/fraudbusters-management
      valitydev/fraudbusters-mg-connector
      valitydev/fraudbusters-notificator
      valitydev/fraudbusters-warehouse
      valitydev/fraudo
      valitydev/geck
      valitydev/hooker
      valitydev/kafka-common-lib
      valitydev/machinarium
      valitydev/magista
      valitydev/magista-dsl
      valitydev/mamsel
      valitydev/mg-event-sink-listener-spring-boot-starter
      valitydev/newway
      valitydev/org-manager
      valitydev/party-shop
      valitydev/payout-manager
      valitydev/pg-embedded-plugin
      valitydev/proxy-mocket-inspector
      valitydev/proxy-mocketbank
      valitydev/proxy-mocketbank-mpi
      valitydev/registry-payout-worker
      valitydev/scheduled-payout-worker
      valitydev/scrooge
      valitydev/shumway
      valitydev/sink-common-lib
      valitydev/testcontainers-annotations
      valitydev/trusted-tokens-manager
      valitydev/vality-http-client
      valitydev/wb-list-manager
      valitydev/woody_java
      valitydev/xrates
