group:
  - id: default
    files:
      - source: workflows/base/basic-linters.yml
        dest: .github/workflows/basic-linters.yml
      - source: LICENSE
        dest: LICENSE
      - source: .github/settings.yml
        replace: false
    repos: |-
      valitydev/.allstar
      valitydev/.github
      valitydev/account-balance-proto
      valitydev/action-autotag
      valitydev/action-deploy-docker
      valitydev/action-deploy-jdk-package
      valitydev/action-download-file
      valitydev/action-frontend
      valitydev/action-jdk-build
      valitydev/action-setup-swagger-codegen
      valitydev/action-setup-thrift
      valitydev/adapter-bank-payout-spring-boot-starter
      valitydev/adapter-bank-spring-boot-starter
      valitydev/adapter-bank-spring-boot-starter-test
      valitydev/adapter-client-lib
      valitydev/adapter-common-lib
      valitydev/adapter-flow-lib
      valitydev/adapter-thrift-lib
      valitydev/analytics
      valitydev/analytics-proto
      valitydev/anapi-v1
      valitydev/anapi-v2
      valitydev/ank-proto
      valitydev/base-workflows
      valitydev/bender-proto
      valitydev/binbase-proto
      valitydev/bouncer
      valitydev/bouncer-client-erlang
      valitydev/bouncer-policies
      valitydev/bouncer-proto
      valitydev/capi-pcidss-v2
      valitydev/capi-v2
      valitydev/cashreg-proto
      valitydev/cds-proto
      valitydev/charts
      valitydev/checkout
      valitydev/claim-management
      valitydev/clamav
      valitydev/clickhouse-test
      valitydev/columbus
      valitydev/columbus-proto
      valitydev/configurations
      valitydev/control-center
      valitydev/damsel
      valitydev/dashboard
      valitydev/db-common-lib
      valitydev/deanonimus
      valitydev/deanonimus-proto
      valitydev/dmt_client
      valitydev/dominant
      valitydev/dominant-cache
      valitydev/dominant-cache-proto
      valitydev/erlang-templates
      valitydev/erlang-workflows
      valitydev/error-mapping-java
      valitydev/fault-detector
      valitydev/fault-detector-proto
      valitydev/file-storage-proto
      valitydev/fistful-magista
      valitydev/fistful-proto
      valitydev/fistful-reporter
      valitydev/fistful-reporter-proto
      valitydev/fistful-server
      valitydev/fraudbusters
      valitydev/fraudbusters-api
      valitydev/fraudbusters-compose
      valitydev/fraudbusters-examples
      valitydev/fraudbusters-management
      valitydev/fraudbusters-mg-connector
      valitydev/fraudbusters-notificator
      valitydev/fraudbusters-notificator-proto
      valitydev/fraudbusters-proto
      valitydev/fraudbusters-ui
      valitydev/fraudbusters-warehouse
      valitydev/fraudbusters-warehouse-proto
      valitydev/fraudo
      valitydev/frontend-openapi-generator-cli
      valitydev/frontend-thrift-codegen
      valitydev/geck
      valitydev/hellgate
      valitydev/homebrew-tap
      valitydev/hooker
      valitydev/identdocstore-proto
      valitydev/identification-proto
      valitydev/image-riak-base
      valitydev/iosetopts
      valitydev/java-checkstyle-config
      valitydev/java-service-dependencies
      valitydev/java-shared-resources
      valitydev/java-workflow
      valitydev/kafka-common-lib
      valitydev/kafka-connect-image
      valitydev/library-parent-pom
      valitydev/limiter-proto
      valitydev/machinarium
      valitydev/machinegun
      valitydev/machinegun-core
      valitydev/machinegun-proto
      valitydev/magista
      valitydev/magista-dsl
      valitydev/magista-proto
      valitydev/mamsel
      valitydev/messages-proto
      valitydev/mg-event-sink-listener-spring-boot-starter
      valitydev/midgard-proto
      valitydev/moneypenny-proto
      valitydev/msgpack-proto
      valitydev/mvnotify
      valitydev/newway
      valitydev/notification-proto
      valitydev/org-management-proto
      valitydev/org-manager
      valitydev/party-management
      valitydev/party-shop
      valitydev/party-shop-proto
      valitydev/pathfinder_proto
      valitydev/payout-manager
      valitydev/payout-manager-proto
      valitydev/pg-embedded-plugin
      valitydev/proxy-mocket-inspector
      valitydev/proxy-mocketbank
      valitydev/proxy-mocketbank-mpi
      valitydev/pstds-proto
      valitydev/questionary-aggr-proto
      valitydev/registry-payout-worker
      valitydev/reporter-proto
      valitydev/schedulator-proto
      valitydev/scheduled-payout-worker
      valitydev/scrooge
      valitydev/service-parent-pom
      valitydev/shumaich-proto
      valitydev/shumway
      valitydev/sink-common-lib
      valitydev/swag-analytics
      valitydev/swag-anapi-v2
      valitydev/swag-dark-api
      valitydev/swag-fraudbusters
      valitydev/swag-fraudbusters-management
      valitydev/swag-messages
      valitydev/swag-notification
      valitydev/swag-payments
      valitydev/swag-questionary
      valitydev/swag-questionary-aggr-proxy
      valitydev/swag-url-shortener
      valitydev/swag-wallets
      valitydev/swag-wallets-webhook-events
      valitydev/swag-webhook-events
      valitydev/swagger-generator-erlang
      valitydev/tds-proto
      valitydev/test-repo
      valitydev/testcontainers-annotations
      valitydev/three-ds-server-storage-proto
      valitydev/token-keeper
      valitydev/token-keeper-client
      valitydev/token-keeper-proto
      valitydev/trusted-tokens-manager
      valitydev/trusted-tokens-proto
      valitydev/url-shortener
      valitydev/vality-http-client
      valitydev/vality.dev
      valitydev/wallets-hooker
      valitydev/wapi-pcidss-v0
      valitydev/wapi-v0
      valitydev/wapi_lib
      valitydev/wb-list-manager
      valitydev/wb-list-proto
      valitydev/webhook-dispatcher-proto
      valitydev/woody_erlang
      valitydev/woody_java
      valitydev/woorl
      valitydev/xrates
      valitydev/xrates-proto
  - id: proto
    files:
      - source: workflows/proto/
        dest: .github/workflows/
        deleteOrphaned: true
        exclude: |
          basic-linters.yml
    repos: |-
      valitydev/account-balance-proto
      valitydev/analytics-proto
      valitydev/ank-proto
      valitydev/bender-proto
      valitydev/binbase-proto
      valitydev/bouncer-proto
      valitydev/cashreg-proto
      valitydev/cds-proto
      valitydev/damsel
      valitydev/deanonimus-proto
      valitydev/dominant-cache-proto
      valitydev/fault-detector-proto
      valitydev/file-storage-proto
      valitydev/fistful-proto
      valitydev/fistful-reporter-proto
      valitydev/fraudbusters-notificator-proto
      valitydev/fraudbusters-proto
      valitydev/fraudbusters-warehouse-proto
      valitydev/identdocstore-proto
      valitydev/identification-proto
      valitydev/limiter-proto
      valitydev/machinegun-proto
      valitydev/magista-proto
      valitydev/messages-proto
      valitydev/midgard-proto
      valitydev/notification-proto
      valitydev/pathfinder_proto
      valitydev/payout-manager-proto
      valitydev/pstds-proto
      valitydev/questionary-aggr-proto
      valitydev/reporter-proto
      valitydev/schedulator-proto
      valitydev/shumaich-proto
      valitydev/three-ds-server-storage-proto
      valitydev/token-keeper-proto
      valitydev/trusted-tokens-proto
      valitydev/wb-list-proto
      valitydev/webhook-dispatcher-proto
      valitydev/xrates-proto
  - id: java
    files:
      - source: codeowners/java
        dest: CODEOWNERS
        replace: false
    repos: |-
      valitydev/adapter-bank-payout-spring-boot-starter
      valitydev/adapter-bank-spring-boot-starter
      valitydev/adapter-bank-spring-boot-starter-test
      valitydev/adapter-client-lib
      valitydev/adapter-common-lib
      valitydev/adapter-flow-lib
      valitydev/adapter-thrift-lib
      valitydev/analytics
      valitydev/anapi-v2
      valitydev/claim-management
      valitydev/clickhouse-test
      valitydev/columbus
      valitydev/db-common-lib
      valitydev/deanonimus
      valitydev/error-mapping-java
      valitydev/fault-detector
      valitydev/fistful-magista
      valitydev/fistful-reporter
      valitydev/fraudbusters
      valitydev/fraudbusters-api
      valitydev/fraudbusters-examples
      valitydev/fraudbusters-management
      valitydev/fraudbusters-mg-connector
      valitydev/fraudbusters-notificator
      valitydev/fraudbusters-warehouse
      valitydev/fraudo
      valitydev/geck
      valitydev/hooker
      valitydev/kafka-common-lib
      valitydev/machinarium
      valitydev/magista
      valitydev/magista-dsl
      valitydev/mamsel
      valitydev/mg-event-sink-listener-spring-boot-starter
      valitydev/newway
      valitydev/org-manager
      valitydev/party-shop
      valitydev/payout-manager
      valitydev/pg-embedded-plugin
      valitydev/proxy-mocket-inspector
      valitydev/proxy-mocketbank
      valitydev/proxy-mocketbank-mpi
      valitydev/registry-payout-worker
      valitydev/scheduled-payout-worker
      valitydev/scrooge
      valitydev/shumway
      valitydev/sink-common-lib
      valitydev/testcontainers-annotations
      valitydev/trusted-tokens-manager
      valitydev/vality-http-client
      valitydev/wallets-hooker
      valitydev/wb-list-manager
      valitydev/woody_java
      valitydev/xrates
