group:
  - id: default
    files:
      - source: templates/default/
        dest: .
    repos: |-
      valitydev/xrates-proto
  - id: proto
    files:
      - source: workflows/proto/
        dest: .github/workflows/
        deleteOrphaned: true
        exclude: |
          basic-linters.yml
    repos: |-
      valitydev/xrates-proto
