group:
  - id: default
    files:
      - source: workflows/base/basic-linters.yml
        dest: .github/workflows/basic-linters.yml
      - source: LICENSE
        dest: LICENSE
      - source: .github/settings.yml
        replace: false
    repos: |-
      valitydev/xrates-proto
  - id: proto
    files:
      - source: workflows/proto/
        dest: .github/workflows/
        deleteOrphaned: true
        exclude: |
          basic-linters.yml
    repos: |-
      valitydev/xrates-proto
