group:
  - id: default
    files:
      - source: templates/default/
        dest: .
    repos: |-
      valitydev/xrates-proto
  - id: proto
    files:
      - source: templates/proto/
        dest: .
    repos: |-
      valitydev/xrates-proto
