group:
  - id: default
    files:
      - source: workflows/base/basic-linters.yml
        dest: .github/workflows/basic-linters.yml
      - source: LICENSE
        dest: LICENSE
    repos: |-
      valitydev/damsel
      valitydev/newway
  - id: proto
    files:
      - source: workflows/proto/
        dest: .github/workflows/
        deleteOrphaned: true
        exclude: |
          basic-linters.yml
    repos: |-
      valitydev/account-balance-proto
      valitydev/analytics-proto
      valitydev/ank-proto
      valitydev/bender-proto
      valitydev/binbase-proto
      valitydev/bouncer-proto
      valitydev/cashreg-proto
      valitydev/cds-proto
      valitydev/damsel
      valitydev/deanonimus-proto
      valitydev/dominant-cache-proto
      valitydev/fault-detector-proto
      valitydev/file-storage-proto
      valitydev/fistful-proto
      valitydev/fistful-reporter-proto
      valitydev/fraudbusters-notificator-proto
      valitydev/fraudbusters-proto
      valitydev/fraudbusters-warehouse-proto
      valitydev/identdocstore-proto
      valitydev/identification-proto
      valitydev/limiter-proto
      valitydev/machinegun-proto
      valitydev/magista-proto
      valitydev/messages-proto
      valitydev/midgard-proto
      valitydev/notification-proto
      valitydev/pathfinder_proto
      valitydev/payout-manager-proto
      valitydev/pstds-proto
      valitydev/questionary-aggr-proto
      valitydev/reporter-proto
      valitydev/schedulator-proto
      valitydev/shumaich-proto
      valitydev/three-ds-server-storage-proto
      valitydev/token-keeper-proto
      valitydev/trusted-tokens-proto
      valitydev/wb-list-proto
      valitydev/webhook-dispatcher-proto
      valitydev/xrates-proto
  - id: java
    files:
      - source: codeowners/java
        dest: CODEOWNERS
        replace: false
    repos: valitydev/newway
